package com.example.lightweightyoutube.data.network

import android.content.Context
import com.example.lightweightyoutube.BuildConfig // Will be generated by AGP
import com.example.lightweightyoutube.data.preferences.InvidiousPreferences
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.concurrent.TimeUnit

/**
 * Singleton object responsible for creating and configuring Retrofit instances
 * for interacting with the Invidious API.
 * It handles dynamic base URLs based on user-selected or default Invidious instances.
 */
object RetrofitClient {

    private const val DEFAULT_TIMEOUT_SECONDS = 30L // Default timeout for network operations.
    private const val STATS_CHECK_TIMEOUT_SECONDS = 10L // Shorter timeout for instance health checks.

    /**
     * Creates an [OkHttpClient] with logging interceptor and timeouts.
     * @param forStatsCheck If true, uses a shorter timeout suitable for quick instance health checks.
     * @return A configured [OkHttpClient] instance.
     */
    private fun createOkHttpClient(forStatsCheck: Boolean = false): OkHttpClient {
        val loggingInterceptor = HttpLoggingInterceptor().apply {
            // Log request/response body in debug builds, none in release.
            level = if (BuildConfig.DEBUG) {
                HttpLoggingInterceptor.Level.BODY
            } else {
                HttpLoggingInterceptor.Level.NONE
            }
        }

        val timeout = if (forStatsCheck) STATS_CHECK_TIMEOUT_SECONDS else DEFAULT_TIMEOUT_SECONDS

        return OkHttpClient.Builder()
            .addInterceptor(loggingInterceptor)
            .connectTimeout(timeout, TimeUnit.SECONDS)
            .readTimeout(timeout, TimeUnit.SECONDS)
            .writeTimeout(timeout, TimeUnit.SECONDS)
            .retryOnConnectionFailure(true) // Enable retrying on connection failures
            .build()
    }

    /**
     * Provides an [InvidiousApiService] instance configured with the user's selected
     * Invidious instance URL (or a default if none is selected).
     *
     * @param context The application context, used to access [InvidiousPreferences].
     * @return A configured [InvidiousApiService] ready for making API calls.
     */
    fun getApiService(context: Context): InvidiousApiService {
        val preferences = InvidiousPreferences(context.applicationContext)
        var baseUrl = preferences.selectedInstanceUrl ?: InvidiousPreferences.getDefaultInstanceUrl()

        // Ensure base URL ends with a slash for Retrofit compatibility.
        if (!baseUrl.endsWith("/")) {
            baseUrl += "/"
        }

        return Retrofit.Builder()
            .baseUrl(baseUrl)
            .client(createOkHttpClient()) // Use default timeout
            .addConverterFactory(GsonConverterFactory.create()) // For JSON parsing
            .build()
            .create(InvidiousApiService::class.java)
    }

    /**
     * Provides an [InvidiousApiService] instance for a specific Invidious instance URL.
     * Useful for testing individual instances (e.g., for health checks in settings).
     * Uses a shorter timeout for quicker checks.
     *
     * @param instanceUrl The base URL of the Invidious instance to connect to.
     * @return A configured [InvidiousApiService].
     */
    fun getApiServiceForInstance(instanceUrl: String): InvidiousApiService {
        var baseUrl = instanceUrl.trim() // Trim whitespace

        // Ensure the URL has a scheme (http or https), defaulting to https.
        if (!baseUrl.startsWith("http://", ignoreCase = true) && !baseUrl.startsWith("https://", ignoreCase = true)) {
            baseUrl = "https://$baseUrl"
        }

        // Ensure base URL ends with a slash.
        if (!baseUrl.endsWith("/")) {
            baseUrl += "/"
        }

        return Retrofit.Builder()
            .baseUrl(baseUrl)
            .client(createOkHttpClient(forStatsCheck = true)) // Use shorter timeout for stats check
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(InvidiousApiService::class.java)
    }
}
